/**
 * Created by yishan on 17/3/8.
 */
var infoData =

    [
        {
            "id": 1,
            "name": "音标",
            "alias": "yinbiao",
            "view": 7461,
            "videoInfoList": [
                {
                    "id": 13,
                    "title": "零基础学习英语音标视频教程",
                    "cover": "http://english.6ag.cn/uploads/video-info/74ceb292408d6718cb818293b039c5e2.jpg",
                    "view": 5628,
                    "teacherName": "Nickcen",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 16,
                    "commentCount": 19,
                    "collectionCount": 0
                },
                {
                    "id": 12,
                    "title": "48个国际音标发音视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/f05d2843f5ecf9ec9448c98a9e6bbe80.jpg",
                    "view": 1929,
                    "teacherName": "佚名",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 21,
                    "commentCount": 10,
                    "collectionCount": 0
                },
                {
                    "id": 11,
                    "title": "赖世雄美语音标视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/ac10f838d75821919094ae0f0fe98878.jpg",
                    "view": 527,
                    "teacherName": "赖世雄",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 3,
                    "commentCount": 3,
                    "collectionCount": 0
                },
                {
                    "id": 10,
                    "title": "谢孟媛kk音标教学视频全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/f5135950a08d7a8bf1309194c28c5e39.jpg",
                    "view": 1052,
                    "teacherName": "谢孟媛",
                    "videoType": "youku",
                    "recommended": 1,
                    "collected": 0,
                    "videoCount": 10,
                    "commentCount": 1,
                    "collectionCount": 0
                },
                {
                    "id": 9,
                    "title": "小学生快乐学音标视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/ff30059e4c5eee41208fd777ab16222c.jpg",
                    "view": 257,
                    "teacherName": "佚名",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 5,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 8,
                    "title": "傻瓜国际音标视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/4a3e2eec52083e5d67c76d6b3af59466.jpg",
                    "view": 169,
                    "teacherName": "海伦",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 8,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 7,
                    "title": "郝彬英语音标学习视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/7115860db946dfe4fb503076a6a6c8ff.jpg",
                    "view": 96,
                    "teacherName": "郝彬 ",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 10,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 6,
                    "title": "国际音标教学视频全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/1f7211ba0bb2170d74da5f325c4550ca.jpg",
                    "view": 193,
                    "teacherName": "夏川",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 36,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 5,
                    "title": "英语音标基础入门视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/25dfcee195a14f613b7e71f53dea0f52.jpg",
                    "view": 167,
                    "teacherName": "Nickcen",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 18,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 4,
                    "title": "少儿国际音标视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/ea2366f43506e54567740545aa30e32a.jpg",
                    "view": 121,
                    "teacherName": "佚名",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 24,
                    "commentCount": 0,
                    "collectionCount": 0
                }
            ]
        },
        {
            "id": 2,
            "name": "单词",
            "alias": "danci",
            "view": 5827,
            "videoInfoList": [
                {
                    "id": 87,
                    "title": "英语单词拼读视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/245894d3fc2312adc2df4d70ac38abfe.jpg",
                    "view": 2089,
                    "teacherName": "阿明",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 15,
                    "commentCount": 1,
                    "collectionCount": 0
                },
                {
                    "id": 86,
                    "title": "快速记单词视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/feef4bc8174da15db4207262d38f980f.jpg",
                    "view": 1148,
                    "teacherName": "阿明",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 14,
                    "commentCount": 2,
                    "collectionCount": 0
                },
                {
                    "id": 85,
                    "title": "英语词汇立体记忆视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/d868c261f412f2c728c40ad2944e8b5e.jpg",
                    "view": 272,
                    "teacherName": "刘莉",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 50,
                    "commentCount": 1,
                    "collectionCount": 0
                },
                {
                    "id": 84,
                    "title": "零起步学英语单词视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/105091a820f208c7e2714723dfa70328.jpg",
                    "view": 700,
                    "teacherName": "刘悦",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 30,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 83,
                    "title": "英语六级词汇视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/87d19ccd505c09c9e0f493da197c7ce6.jpg",
                    "view": 89,
                    "teacherName": "周思成",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 13,
                    "commentCount": 1,
                    "collectionCount": 0
                },
                {
                    "id": 82,
                    "title": "英语四级词汇视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/e55c2ccf508f990e9a3b95bd4181ca63.jpg",
                    "view": 198,
                    "teacherName": "闫文军",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 8,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 81,
                    "title": "考研英语基础班词汇视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/59891f290c44810f1602dd138a207baf.jpg",
                    "view": 47,
                    "teacherName": "李伟",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 8,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 80,
                    "title": "东方贺教你背单词视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/141b7790920ef24779df65aecb857e8d.jpg",
                    "view": 94,
                    "teacherName": "东方贺",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 91,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 79,
                    "title": "阿明帮你背单词视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/693da7d26021af461658b5205501567d.jpg",
                    "view": 57,
                    "teacherName": "阿明",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 9,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 78,
                    "title": "教你背单词视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/62ff33e11824856894387e689b257ea2.jpg",
                    "view": 99,
                    "teacherName": "蒋慧",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 21,
                    "commentCount": 3,
                    "collectionCount": 0
                }
            ]
        },
        {
            "id": 3,
            "name": "语法",
            "alias": "yufa",
            "view": 4206,
            "videoInfoList": [
                {
                    "id": 139,
                    "title": "初中英语语法大全视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/7e6792475241be93c33070a96cfd059a.jpg",
                    "view": 1127,
                    "teacherName": "阿明",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 65,
                    "commentCount": 4,
                    "collectionCount": 0
                },
                {
                    "id": 138,
                    "title": "英语语法入门视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/fb11223b0d8f2f0820aad4640718ef21.jpg",
                    "view": 1128,
                    "teacherName": "Nick cen",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 28,
                    "commentCount": 6,
                    "collectionCount": 0
                },
                {
                    "id": 137,
                    "title": "崔荣容英语语法学习视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/78e465cf2de8f5992d34e089f85b616c.jpg",
                    "view": 2137,
                    "teacherName": "崔荣容",
                    "videoType": "youku",
                    "recommended": 1,
                    "collected": 0,
                    "videoCount": 50,
                    "commentCount": 3,
                    "collectionCount": 0
                },
                {
                    "id": 136,
                    "title": "英语语法讲座（美语）视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/804698326701e19b394c1019fb3e0b8b.jpg",
                    "view": 159,
                    "teacherName": "佚名",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 10,
                    "commentCount": 1,
                    "collectionCount": 0
                },
                {
                    "id": 135,
                    "title": "大学英语语法视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/282e6bcc6badc5f87f2352db68111447.jpg",
                    "view": 92,
                    "teacherName": "吴军赞",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 10,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 134,
                    "title": "学位英语三级语法视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/26d93fbcc918cfa3b0d5663f322e006d.jpg",
                    "view": 48,
                    "teacherName": "佚名",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 27,
                    "commentCount": 4,
                    "collectionCount": 0
                },
                {
                    "id": 133,
                    "title": "初中英语语法视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/ee3676d6d1d8ccb55abb7dc63da5a145.jpg",
                    "view": 86,
                    "teacherName": "佚名",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 25,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 132,
                    "title": "高中英语语法视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/a51376da2e331b171b4ee141e1c9abf7.jpg",
                    "view": 86,
                    "teacherName": "佚名",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 15,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 131,
                    "title": "谢孟媛初级语法视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/68c2c3af537fed03b3b02abefefb8660.jpg",
                    "view": 939,
                    "teacherName": "谢孟媛",
                    "videoType": "youku",
                    "recommended": 1,
                    "collected": 0,
                    "videoCount": 60,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 130,
                    "title": "考研英语语法10天速成视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/b6c50a414a4b7c3682c1b637eaf6ec43.jpg",
                    "view": 47,
                    "teacherName": "佚名",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 10,
                    "commentCount": 0,
                    "collectionCount": 0
                }
            ]
        },
        {
            "id": 4,
            "name": "口语",
            "alias": "kouyu",
            "view": 3052,
            "videoInfoList": [
                {
                    "id": 63,
                    "title": "常用英语口语100句视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/b3f78038c10877d73e4a5809d0331b65.jpg",
                    "view": 1305,
                    "teacherName": "佚名",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 20,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 62,
                    "title": "英语情景口语速成视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/ce1720e649aae99bb666c8b208a95b9d.jpg",
                    "view": 522,
                    "teacherName": "郝彬",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 16,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 61,
                    "title": "超级口语秀视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/2fbec355859d4c2bf9ad6c77802a8ab4.jpg",
                    "view": 187,
                    "teacherName": "海伦",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 12,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 60,
                    "title": "老外教你说口语视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/e29034b604f3e66d9cd9efd25e5aa145.jpg",
                    "view": 423,
                    "teacherName": "佚名",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 59,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 59,
                    "title": "走向未来英语口语视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/280561633b656c6d67f2f978b73e06d0.jpg",
                    "view": 56,
                    "teacherName": "佚名",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 60,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 58,
                    "title": "剑桥英语之应急英语视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/e7263951140ec28a5971e2e18839baef.jpg",
                    "view": 36,
                    "teacherName": "佚名",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 63,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 57,
                    "title": "雅思口语视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/fb945627376541a9ab965b82305bcc82.jpg",
                    "view": 101,
                    "teacherName": "战阳",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 41,
                    "commentCount": 1,
                    "collectionCount": 0
                },
                {
                    "id": 56,
                    "title": "李阳疯狂英语口语速成视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/3da892c0cbac95f261a42e22d819e708.jpg",
                    "view": 136,
                    "teacherName": "李阳",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 12,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 55,
                    "title": "日常英语口语讲座视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/8eda3e921f47876b5bc3b2195b9aa66a.jpg",
                    "view": 47,
                    "teacherName": "佚名",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 11,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 54,
                    "title": "新英语900句视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/28088aaf3d257cc0b8c4ae996e449000.jpg",
                    "view": 78,
                    "teacherName": "Lily",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 59,
                    "commentCount": 0,
                    "collectionCount": 0
                }
            ]
        },
        {
            "id": 5,
            "name": "听力",
            "alias": "tingli",
            "view": 1825,
            "videoInfoList": [
                {
                    "id": 102,
                    "title": "雅思听力视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/9189eb5dcc04b9c477dd35b5f0b33eed.jpg",
                    "view": 702,
                    "teacherName": "汤洁",
                    "videoType": "youku",
                    "recommended": 1,
                    "collected": 0,
                    "videoCount": 35,
                    "commentCount": 2,
                    "collectionCount": 0
                },
                {
                    "id": 101,
                    "title": "托福听力视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/12cdbad545193d158e8f44bb039edb1d.jpg",
                    "view": 103,
                    "teacherName": "高勇",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 14,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 100,
                    "title": "英语六级听力视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/7b623a3c2500e8b5582ecbb9708cc4c1.jpg",
                    "view": 78,
                    "teacherName": "周冰",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 2,
                    "commentCount": 1,
                    "collectionCount": 0
                },
                {
                    "id": 99,
                    "title": "英语四级听力视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/1535bca20c25bacaf80c3ddd1888ec8e.jpg",
                    "view": 120,
                    "teacherName": "周冰",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 12,
                    "commentCount": 1,
                    "collectionCount": 0
                },
                {
                    "id": 98,
                    "title": "英语听力突破策略视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/664063cb7ecfb8f25873c190a0a2ee41.jpg",
                    "view": 61,
                    "teacherName": "佚名",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 4,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 97,
                    "title": "托福听力精选视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/fecf9d018c633b7287b2c7b22d9c5dd7.jpg",
                    "view": 10,
                    "teacherName": "佚名",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 98,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 96,
                    "title": "英语六级听力视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/2ced7f96695830d69f23a9cd5de33d78.jpg",
                    "view": 14,
                    "teacherName": "佚名",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 64,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 95,
                    "title": "高中英语听力满分攻略标准训练视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/979765b83ba17d893a7d5a34995a4629.jpg",
                    "view": 9,
                    "teacherName": "佚名",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 110,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 94,
                    "title": "高中英语听力满分攻略强化训练视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/e9978add42c1bc0a9e530c3deae91b84.jpg",
                    "view": 78,
                    "teacherName": "佚名",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 110,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 93,
                    "title": "新东方英语四级听力视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/b772cee13ccb0a856387b697d0067dbf.jpg",
                    "view": 25,
                    "teacherName": "赵建昆",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 84,
                    "commentCount": 0,
                    "collectionCount": 0
                }
            ]
        },
        {
            "id": 6,
            "name": "阅读",
            "alias": "yuedu",
            "view": 1135,
            "videoInfoList": [
                {
                    "id": 112,
                    "title": "2016考研英语作文视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/4aabbaae3db049bf7686c588267d1b14.jpg",
                    "view": 123,
                    "teacherName": "何凯文",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 5,
                    "commentCount": 2,
                    "collectionCount": 0
                },
                {
                    "id": 111,
                    "title": "雅思阅读视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/1c6b20898c55482f85b3139a4c32e326.jpg",
                    "view": 100,
                    "teacherName": "史心语",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 35,
                    "commentCount": 1,
                    "collectionCount": 0
                },
                {
                    "id": 110,
                    "title": "托福阅读视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/c36eef352abc620f3447b0a37e24ffea.jpg",
                    "view": 74,
                    "teacherName": "李静超",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 10,
                    "commentCount": 4,
                    "collectionCount": 0
                },
                {
                    "id": 109,
                    "title": "英语四级阅读视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/2e376d888fa571e8285d7f27386e47c9.jpg",
                    "view": 76,
                    "teacherName": "赵南望",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 9,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 108,
                    "title": "英语六级阅读视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/276213853e426702f3a741ab0734400f.jpg",
                    "view": 4,
                    "teacherName": "蒋华",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 2,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 107,
                    "title": "英语三级考试阅读视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/ad4d738ca8fb48906f3d2ac207bb7562.jpg",
                    "view": 22,
                    "teacherName": "佚名",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 31,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 106,
                    "title": "2016考研英语阅读视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/406962c80a0bd5b0fea35f5b094c7864.jpg",
                    "view": 7,
                    "teacherName": "陈正康",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 8,
                    "commentCount": 2,
                    "collectionCount": 0
                },
                {
                    "id": 105,
                    "title": "考研英语阅读基础视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/b15f11429ce78c323135cb418ffca41f.jpg",
                    "view": 5,
                    "teacherName": "曹天啸",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 8,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 104,
                    "title": "考研英语阅读强化精讲视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/f03328d9d41390dd98a99534cdccfc20.jpg",
                    "view": 0,
                    "teacherName": "赵敏",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 5,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 103,
                    "title": "雅思阅读视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/67abf6987bb538f34b74f0741b98279d.jpg",
                    "view": 8,
                    "teacherName": "Nancy",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 30,
                    "commentCount": 0,
                    "collectionCount": 0
                }
            ]
        },
        {
            "id": 7,
            "name": "作文",
            "alias": "zuowen",
            "view": 875,
            "videoInfoList": [
                {
                    "id": 119,
                    "title": "英语写作系列（美语）视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/e39f9884277631168476545059c39727.jpg",
                    "view": 106,
                    "teacherName": "佚名",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 9,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 118,
                    "title": "英文写作视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/77d4a22292b02b04961550423901d290.jpg",
                    "view": 75,
                    "teacherName": "Jamaica Conner",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 9,
                    "commentCount": 1,
                    "collectionCount": 0
                },
                {
                    "id": 117,
                    "title": "英语写作视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/429cc69b74ab36786fedfdc36a4d174b.jpg",
                    "view": 70,
                    "teacherName": "张筝",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 29,
                    "commentCount": 1,
                    "collectionCount": 0
                },
                {
                    "id": 116,
                    "title": "雅思写作视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/b0554ef83214426c506bbeb809ad9b7d.jpg",
                    "view": 47,
                    "teacherName": "Aki",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 28,
                    "commentCount": 1,
                    "collectionCount": 0
                },
                {
                    "id": 115,
                    "title": "托福写作视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/06aaf1aeaaf200c48d0c08efbf9bdef1.jpg",
                    "view": 4,
                    "teacherName": "郑铟",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 11,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 114,
                    "title": "英语四级写作视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/008868ec4fb153f9cfc2ca0adf74427e.jpg",
                    "view": 7,
                    "teacherName": "付博",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 8,
                    "commentCount": 0,
                    "collectionCount": 0
                },
                {
                    "id": 113,
                    "title": "英语六级作文视频教程全集",
                    "cover": "http://english.6ag.cn/uploads/video-info/7065cd58798a8b2159dc5f210da463d4.jpg",
                    "view": 2,
                    "teacherName": "李伟",
                    "videoType": "youku",
                    "recommended": 0,
                    "collected": 0,
                    "videoCount": 2,
                    "commentCount": 0,
                    "collectionCount": 0
                }
            ]
        }
    ]
